
[build]
command = "npm run build"
publish="."
base="/"

[[redirects]]
from = "/home"
to = "/"
status = 200
[[redirects]]
from = "/"
to = "/home"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"